DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
DECLARE BOOKSCOUNT, BK_ID INT;
DECLARE FINISHED INT DEFAULT 0;
DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
OPEN ALL_BOOKS;
IF NOT EXISTS(SELECT 1
              FROM INFORMATION_SCHEMA.COLUMNS
              WHERE upper(TABLE_NAME) = 'BOOKS'
                AND upper(COLUMN_NAME) = 'BESTSELLER') THEN
    ALTER TABLE books add column BESTSELLER boolean DEFAULT false;
END IF;
WHILE (FINISHED = 0) DO
    FETCH ALL_BOOKS INTO BK_ID;
IF (FINISHED = 0) THEN
SELECT COUNT(*) FROM RENTS
WHERE BOOK_ID = BK_ID
INTO BOOKSCOUNT;

UPDATE BOOKS SET BESTSELLER = true
WHERE BOOKSCOUNT > 2 AND BOOK_ID = BK_ID;
COMMIT;
END IF;
END WHILE;
CLOSE ALL_BOOKS;
END $$;

DELIMITER ;

CALL UpdateBestsellers();
SELECT * FROM books

