EXPLAIN SELECT * FROM READERS
WHERE FIRSTNAME = 'John';

CREATE INDEX NAMENO ON READERS (FIRSTNAME, LASTNAME);
CREATE INDEX TITLENO ON BOOKS (TITLE);

EXPLAIN SELECT * FROM READERS
WHERE FIRSTNAME = 'John';